name = "GracefulPkg"
uuid = "828d9ff0-206c-6161-646e-6576656f7244"
license = "MIT"
authors = ["Fons van der Plas <fons@plutojl.org>"]
version = "0.1.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Pkg = "1"
julia = "1.10"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Test"]
